holidays = [
    2025-12-24,
    2025-12-25,
    2026-01-01,
    2026-01-10,
    2026-04-03,
    2026-05-25,
    2026-07-03,
    2026-09-07,
    2026-11-26,
    2026-11-27,
    2026-12-24,
    2026-12-25,
]
